library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/cloudbees-oss/pipeline-home-demo.git',
   credentialsId: 'carlosrodlop-GH'])

gitUrlValidator("${gh_repo}")

def configYaml = """---
k8_agent_yaml : '${k8_agent_yaml}'
g_cred : '${g_cred}'
g_repo : '${g_repo}'
g_branch : ''
dockerfile_path : '${dockerfile_path}'
docker_registry : '${docker_registry}'
"""

mavenK8Project(configYaml)