library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/carlosrodlop/my-pipeline-home.git',
   credentialsId: 'carlosrodlop-GH'])

def configYaml = """---
k8_agent_yaml : '${k8_agent_yaml}'
gh_cred : '${gh_cred}'
gh_repo : '${gh_repo}'
gh_branch : ''
dockerfile_path : '${dockerfile_path}'
docker_registry : '${docker_registry}'
"""

mavenK8Project(configYaml)