library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/carlosrodlop/my-pipeline-home.git',
   credentialsId: 'carlosrodlop-GH'])

buildAgentKanikoProject {
    k8_agent_yaml = "agents/pods/maven-kaniko.yaml"
    gh_cred = "carlosrodlop-GH"
    gh_repo = "https://github.com/carlosrodlop/simple-app.git"
    docker_registry = "${docker_registry}"
    docker_image = "${docker_image}"
    docker_tag = "${docker_tag}"
}