library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/carlosrodlop/my-pipeline-home.git',
   credentialsId: 'carlosrodlop-GH'])

buildAgentKanikoProject {
    

    
		docker_registry = "${docker_registry}"
    docker_image = "${docker_image}"
    docker_tag = "${docker_tag}"

}