// Loading Shared Libraries
library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/cloudbees-oss/pipeline-home-demo.git',
   credentialsId: 'carlosrodlop-GH'])

// Template Form Validation
strNoSpacesValidator("Git Repository URL", "${g_url}")
strNoSpacesValidator("Git Branch", "${g_branch}")
strNoSpacesValidator("Docker Registry", "${d_registry}")
gitUrlValidator("Git Repository URL", 
                  "${g_url}",
                  "",
                  "")

// Building the data object
def configYaml = """---
k8_agent_yaml : '${k8_agent_yaml}'
g_cred : '${g_cred}'
g_repo : '${g_url}'
g_branch : '${g_branch}'
d_path : '${d_path}'
d_latest : ${d_latest}
d_registry : '${d_registry}'
"""

// Calling the CI Pipeline
mavenK8Project(configYaml)