
---
apiVersion: v1
kind: "PersistentVolumeClaim"
metadata: 
  name: "maven-pv-claim"
  # namespace: "belgium-dialga-agents"
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi