library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/carlosrodlop/my-shared-libraries.git',
   credentialsId: 'carlosrodlop-GH'])

buildAgentKanikoProject {
    k8_secret = "supportbeescloud"
		docker_registry = "supportbeescloud"
    docker_image = "python-agent"
    docker_tag = "0.2"
    agent_tools = "apt-get update && apt-get install python"
		team_name = "Phyton Team"
    team_mail = "phyton-team@mail.com"
}