// Loading Shared Libraries
library identifier: 'my-shared-libraries@demo', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/cloudbees-oss/pipeline-home-demo.git',
   credentialsId: '6a998a68-1b08-4397-9278-49a3fda95bb8'])

// Template Form Validation
strNoSpacesValidator("GitHub Repository Name", "${ghe_repo}")
strNoSpacesValidator("Docker Registry", "${d_registry}")
gitUrlValidator("GitHub Repository Name",
              "${ghe_repo}",
              "support-team",
              "https://github.example.com/api/v3")

// Building the data object
def configYaml = """---
k8_agent_yaml : '${k8_agent_yaml}'
ghe_cred : '${ghe_cred}'
ghe_repo : '${ghe_repo}'
d_path : '${d_path}'
d_latest : ${d_latest}
d_registry : '${d_registry}'
"""

// Calling the CI Pipeline
mavenK8Project(configYaml)