// Loading Shared Libraries
library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/cloudbees-oss/pipeline-home-demo.git',
   credentialsId: 'carlosrodlop-GH'])

// Form Validation
strNoSpacesValidator("GitHub Repository Name", "${ghe_repo}")
strNoSpacesValidator("Docker Registry", "${d_registry}")
gitUrlValidator("GitHub Repository Name",
              "${ghe_repo}",
              "support-team",
              "https://github.beescloud.com/api/v3")

// Building the data object
def configYaml = """---
k8_agent_yaml : '${k8_agent_yaml}'
g_cred : '${ghe_cred}'
g_repo : '${ghe_repo}'
g_branch : ''
d_path : '${d_path}'
d_latest : ${d_latest}
d_registry : '${d_registry}'
"""

// Running the CI Pipeline
mavenK8Project(configYaml)