
---
kind: Pod
metadata:
  name: "git, maven and kaniko"
spec:
  containers:
  - name: "maven"
    image: "maven:3.6.3-jdk-8"
    command:
    - bash
    tty: true
  - name: "kaniko"
    image: "gcr.io/kaniko-project/executor:debug"
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: "ci-docker-cfg"
        mountPath: "/kaniko/.docker"
  volumes:
  - name: "ci-docker-cfg"
    projected:
      sources:
      - secret:
          name: "docker-rye" # existing kubernetes secret for login into the Docker Registry
          items:
            - key: ".dockerconfigjson"
              path: "config.json"