library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/carlosrodlop/my-shared-libraries.git',
   credentialsId: 'carlosrodlop-GH'])

buildAgentKanikoProject {
    k8_secret = "${k8_secret}"
		docker_registry = "${docker_registry}"
    docker_image = "${docker_image}"
    docker_tag = "${docker_tag}"
    agent_tools = "${agent_tools}"
		team_name = "${team_name}"
    team_mail = "${team_mail}"
}